### ISSUE TITLE
Please declare a license

### ISSUE THREAD

**Issue by fredjean** [zchee/docker-machine-driver-xhyve#108]
I am not able to find the license under which you are releasing this (very helpful) code. Could you please add one?

For background, this may prevent some companies with a strong IP and compliance group from being able to use or contribute to this project.

**Comment by zchee** [comment]
@fredjean OK :)

**Comment by fredjean** [comment]
Let me know if you want to discuss which one to use. IANAL, just someone who spent too much time talking with them on licensing...

**Comment by zchee** [comment]
@fredjean Hm, I will add `LICENSE` now. but I do not yet understand the detail of License.

xhyve is BSD(2?3?), Also, a lot of wrote Go language project uses BSD-3 clause.
So, I think better is BSD 3.

WDYT?

**Comment by fredjean** [comment]
Following the lead of the community is generally a good idea. The BSD family of licenses are very permissive and would be a fine choice.

It looks to me that BSD-2 is used by xhyve. (BSD-2 stands for the BSD 2 clause license.)

**Comment by zchee** [comment]
@fredjean OK :) I see.
I'll add BSD 3 license later. Thanks for advice!!

===

FYI, Docker will official supports for OS X near future.
If it's easy to use, I planned to add **deprecated** in README.
Are license changes necessary?

**Comment by fredjean** [comment]
I would still recommend it. Publishing your code on GitHub does not grant any further rights than publishing on GitHub and forking on GitHub. It doesn't allow people to copy, contribute, install. In the US, you retain all rights to your code by default. Adding the license clarifies what your intent is.


この変更を考慮するためにあなたの光一ありがとうございます。 (and many apologies for the poor, automatically translated Japanese.)

**Comment by zchee** [comment]
@fredjean OK, I got it.
Thanks for the easy to understand explanation :)

Also Japanese comments. I not good at English :P

**Comment by zchee** [comment]
@fredjean Added: https://github.com/zchee/docker-machine-driver-xhyve/commit/0ca005ce9fc204478675ac6692585fd4873f668d
