### ISSUE TITLE
go build is broken

### ISSUE THREAD

**Issue by FiloSottile** [zchee/docker-machine-driver-xhyve#115]
```
# github.com/zchee/docker-machine-driver-xhyve/vendor/github.com/hooklift/xhyve
vendor/github.com/hooklift/xhyve/pci_virtio_9p.c:49:10: fatal error: 'lib9p.h' file
      not found
```

However, `make` works.

**Comment by ain** [comment]
Reproduced. 
```
$ go version
go version go1.6.2 darwin/amd64
```

**Comment by huguesalary** [comment]
If you're blocked by this, know that using the provided `Makefile` works.

**Comment by Strech** [comment]
@FiloSottile @ain This is a fix of a brew recipe https://github.com/Homebrew/legacy-homebrew/pull/49467 still not merged 😭

**Comment by zchee** [comment]
@FiloSottile Sorry, this project needs C build for lib9p. Not support go gettable.
