### ISSUE TITLE
Also have Docker Mac beta

### ISSUE THREAD

**Issue by alexellis** [zchee/docker-machine-driver-xhyve#118]
```
docker ps
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
```

Also have Docker Mac beta which crashed, then I tried out this driver again - if I recreate the machine will it upgrade the Docker API version?

**Comment by hpurmann** [comment]
`docker-machine upgrade` could help you I guess ;)

**Comment by alexellis** [comment]
@hpurmann thanks 👍
