### ISSUE TITLE
Recompile on Go 1.7.1 to work on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by annismckenzie** [zchee/docker-machine-driver-xhyve#137]
The current binary doesn't work anymore on macOS Sierra – see https://golang.org/doc/go1.7#ports. They crash with mutex inconsistencies or just plain segfault. You'll need to upgrade to Sierra and upgrade to one of the newest releases of 1.7.1 in order to correctly build a binary that will work on Sierra. As a lot of people are depending on this plugin (the Kubernetes' minikube project comes to mind here) and I have this fixed and running on my machine (refs kubernetes/minikube#646).

**Comment by puja108** [comment]
So after seeing that my local go version was set to 1.4.2 by Sierra I installed a recent go 1.7.1 with homebrew. After a reboot suddenly things are working. So there's no real need for a recompile, you just need a recent go version running. Still quite annoying, if a new binary would work on Sierra ootb that would make things a lot nicer definitely.

**Comment by zchee** [comment]
@annismckenzie @puja108 OK, I know this problem. Just in case, related `gettimeofday` API?
I will release the new version with Go 1.7.1 pre-compile binary later.

**Comment by zchee** [comment]
@annismckenzie @puja108 Ah, sorry forgot.
I developed the qcow2 disk image format, upgrade xhyve to hyperkit and more. Almost finished.

I want to that implements to the new version, So please wait a moment.

**Comment by annismckenzie** [comment]
That sounds awesome – though I'm not in a hurry, it's working for me here. And I'm also just getting started with k8s. Thanks for all the hard work! 💃

**Comment by puja108** [comment]
+1 on what @annismckenzie said. Awesome work @zchee. Though it is currently working for me, trying to stop or delete a VM ended up in the xhyve driver process hanging. Will test out again after your release, anyway tyt.

**Comment by zchee** [comment]
@annismckenzie @puja108 I was released v0.3.0. also released pre-compile binary using go 1.7.3.
Sorry for the delay.
https://github.com/zchee/docker-machine-driver-xhyve/releases/tag/v0.3.0
