### ISSUE TITLE
fatal error: 'stdlib.h' file not found

### ISSUE THREAD

**Issue by justechn** [zchee/docker-machine-driver-xhyve#160]
I am trying to compile this project but I get this error `fatal error: 'stdlib.h' file not found` Can someone help me figure this out?

I am following the instructions in the [readme](https://github.com/zchee/docker-machine-driver-xhyve#install) and when I get to the step `make install` that is when I get the error. 

I should note that I skipped the part about qcow because I don't need that.

Also I am on macOS Sierra Version 10.12.3 and go 1.8

Thanks

**Comment by justechn** [comment]
I figured it out. I had to run `xcode-select --install`

**Comment by Artem85** [comment]
In my case IOS simulator wasn't installed.

Go to Xcode -> Preferences -> Components
Download the latest IOS Simulator.
