### ISSUE TITLE
MAC addresses ending in element with a leading 0 are not mapped to an IP

### ISSUE THREAD

**Issue by juamedgod** [zchee/docker-machine-driver-xhyve#162]
The regular expression cleaning the MAC address in `trimMacAddress` does not clean up the last pair of digits as it expects a colon character. 

This should fix it:
 https://github.com/zchee/docker-machine-driver-xhyve/pull/163

**Comment by zchee** [comment]
Close via https://github.com/zchee/docker-machine-driver-xhyve/pull/163
