### ISSUE TITLE
Project Is dead?

### ISSUE THREAD

**Issue by vyscond** [zchee/docker-machine-driver-xhyve#166]

**Comment by r2d4** [comment]
No?  The last commit was 8 days ago, zchee is an active maintainer

**Comment by zchee** [comment]
@vyscond @r2d4 Yes, still maintain this project.

But yeah, this project has many issues. Related shared directory, network or etc.
Many parts of Docker for Mac are still closed(pinata etc), so this project can be used as an open source's xhyve interface, but there are many bugs.
However, those issues almost from the `C`(xhyve or lib9p) side. They relate to the mach kernel(and IOKit framework) and are not easy to debug.

I'll continue to do my best, but there is too few information about mach kernel and Hypervisor.framework, so fixing those bugs will take a lot of time.

**Comment by vyscond** [comment]
@zchee Didn't notice the last commit date :/
