### ISSUE TITLE
Cannot build with Go and Make

### ISSUE THREAD

**Issue by tomasbasham** [zchee/docker-machine-driver-xhyve#167]
Going through the instructions to build the driver with Go and Make but hitting the following error when running `make install`:

```bash
Tomass-MacBook-Pro docker-machine-driver-xhyve (master)$ make install
==> Build vendor/build/lib9p/lib9p.a...
File "mirage_block_ocaml.ml", line 60, characters 19-33:
Error: Unbound module Block.Config
vendor/github.com/zchee/libhyperkit/xhyve_qcow2.go:5: running "ocamlfind": exit status 2
make: *** [vendor/github.com/zchee/libhyperkit/mirage_block_ocaml.o] Error 1
Tomass-MacBook-Pro docker-machine-driver-xhyve (master)$ 
```

**Comment by tomasbasham** [comment]
Updating OCaml has fixed the issue.

I was on `4.02.2` and updated to `4.04.0`.

**Comment by keyone** [comment]
I have the same error but with OCaml 4.05.0 

→ make install
==> Build vendor/build/lib9p/lib9p.a...
File "mirage_block_ocaml.ml", line 60, characters 19-33:
Error: Unbound module Block.Config
vendor/github.com/zchee/libhyperkit/xhyve_qcow2.go:5: running "ocamlfind": exit status 2
make: *** [vendor/github.com/zchee/libhyperkit/mirage_block_ocaml.o] Error 1
