### ISSUE TITLE
Cut a 0.3.3 Release

### ISSUE THREAD

**Issue by nugend** [zchee/docker-machine-driver-xhyve#178]
The only change in the past two months includes a fix for a startup issue with minikube. I see like 15 or so comments in this thread of people tripping on the issue: https://github.com/kubernetes/minikube/issues/1400#issuecomment-298506787

Pushing out a new version will let them (and me!) get it fixed by brew upgrading this package.

**Comment by scottrigby** [comment]
It would really help adoption. Check out my https://github.com/kubernetes/minikube/issues/1400#issuecomment-311196655 about our workaround.

**Comment by zchee** [comment]
@nugend @scottrigby I’ll release new version after fix travis build error(caused by install OCaml third-party)
Please wait a moment.

**Comment by zchee** [comment]
@nugend @scottrigby Released v0.3.3. Sorry for late...
https://github.com/zchee/docker-machine-driver-xhyve/releases/tag/v0.3.3

**Comment by nugend** [comment]
Reasonable turnaround in my mind! Thanks kindly!
