### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kalbasit** [zchee/docker-machine-driver-xhyve#220]
There's a BUG that's blocking anyone using this project from also using VirtualBox 6 on Darwin. This has been solved over 3 months ago in #214, and yet no release has been cut for it. Is this project still maintained? If not, what is the Docker-blessed way for programmatically installing Docker for Mac? Please do not direct me to download the `.dmg`, it has to be programmatically installed.

Thank you for understanding my frustration!

**Comment by zchee** [comment]
Still maintains. close!!

For another users(means exclude @kalbasit), see
- https://github.com/machine-drivers/docker-machine-driver-xhyve/pull/214#issuecomment-493181669
- https://github.com/machine-drivers/docker-machine-driver-xhyve/pull/214#issuecomment-493182020
- https://github.com/machine-drivers/docker-machine-driver-xhyve/pull/214#issuecomment-493182570
