### ISSUE TITLE
Any plan about HomeBrew formulae support?

### ISSUE THREAD

**Issue by k2wanko** [zchee/docker-machine-driver-xhyve#24]
I am just wondering whether this will support HomeBrew formulae?

**Comment by zchee** [comment]
@k2wanko Thank issue :)

But still this repository is in a development stage.
So, it is difficult to be adopted homebrew.

I think better to create a formula in my repository for now (e.g. `tap zchee/docker-machine-driver-xhyve`)

How do you think?

**Comment by saljam** [comment]
This is now a PR at Homebrew/homebrew#48002. Thanks @zchee for following through with that.

**Comment by zchee** [comment]
@k2wanko @saljam 
Yes. I send a PR.

If that PR has been merged, I will close this issue thread.

**Comment by k2wanko** [comment]
:+1:

**Comment by zchee** [comment]
@k2wanko :)

**Comment by zchee** [comment]
@k2wanko @saljam My pull-request has been merged :)
https://github.com/Homebrew/homebrew/pull/48002
