### ISSUE TITLE
Might want to re-release a binary

### ISSUE THREAD

**Issue by nathanleclaire** [zchee/docker-machine-driver-xhyve#45]
Hey @zchee, we accidentally introduced some regressions in API in latest versions of Machine.  I think you might want to re-compile and re-release the binary for this.  Cheers!

**Comment by zchee** [comment]
@nathanleclaire Thanks!
I think so, too.
Occasionally it seems to fail to build. https://github.com/zchee/docker-machine-driver-xhyve/issues/40

I will prepare for the binary release.
Thanks advise!!

===

Off topic:
Finished remove fork flag.
and, Thanks for add deplicated announce in [README.md](https://github.com/nathanleclaire/docker-machine-xhyve/commit/09bb9d54552e8b171419f2c6e1e62e866f2494cf) :)

**Comment by zchee** [comment]
@nathanleclaire 
I will close this issue when finished binary release.

**Comment by zchee** [comment]
@nathanleclaire I released version v0.2.0!
https://github.com/zchee/docker-machine-driver-xhyve/releases/tag/v0.2.0
Also added pre-compiled binary use travis-release.

Close.
