### ISSUE TITLE
ip not found in dhcp leases

### ISSUE THREAD

**Issue by atomotic** [zchee/docker-machine-driver-xhyve#60]
dhcp problem for me too.

```
(atomotic) DBG | Not there yet 1/60, error: IP not found for MAC 3a:47:46:45:cf:32 in DHCP leases
(atomotic) DBG | operation not supported by device
(atomotic) DBG | xhyve: illegal option -- F
```

following the full debug:

xhyve 

	xhyve -v
	xhyve: 793d17

docker-machine
	
	docker-machine -v
	docker-machine version 0.5.5, build

run

	➜  ~  docker-machine -D create --driver xhyve atomotic
	Docker Machine Version:  0.5.5, build
	Found binary path at /Users/raffaele/go/bin/docker-machine-driver-xhyve
	Launching plugin server for driver xhyve
	Plugin server listening at address 127.0.0.1:61674
	() DBG | operation not supported by device
	() Calling .GetVersion
	Using API Version  1
	() Calling .SetConfigRaw
	() Calling .GetMachineName
	(flag-lookup) Calling .GetCreateFlags
	Found binary path at /Users/raffaele/go/bin/docker-machine-driver-xhyve
	Launching plugin server for driver xhyve
	Plugin server listening at address 127.0.0.1:61678
	() DBG | operation not supported by device
	() Calling .GetVersion
	Using API Version  1
	() Calling .SetConfigRaw
	() Calling .GetMachineName
	(atomotic) Calling .GetMachineName
	(atomotic) Calling .DriverName
	(atomotic) Calling .GetCreateFlags
	(atomotic) Calling .SetConfigFromFlags
	Running pre-create checks...
	(atomotic) Calling .PreCreateCheck
	(atomotic) DBG | ===== Docker Machine xhyve Driver Version 0.2.1 (HEAD) =====
	(atomotic) DBG |
	(atomotic) DBG | executing: /usr/local/bin/VBoxManage -v
	(atomotic) DBG | STDOUT: 5.0.10r104061
	(atomotic) DBG |
	(atomotic) DBG | STDERR:
	(atomotic) Calling .GetConfigRaw
	Creating machine...
	(atomotic) Calling .Create
	(atomotic) DBG | local Boot2Docker ISO version:  v1.9.1
	(atomotic) Copying /Users/raffaele/.docker/machine/cache/boot2docker.iso to /Users/raffaele/.docker/machine/machines/atomotic/boot2docker.iso...
	(atomotic) Creating VM...
	(atomotic) DBG | Mounting boot2docker.iso
	(atomotic) Extracting vmlinuz64 and initrd.img from boot2docker.iso...
	(atomotic) DBG | executing: &{/usr/bin/hdiutil [hdiutil attach /Users/raffaele/.docker/machine/machines/atomotic/boot2docker.iso -mountpoint /Users/raffaele/.docker/machine/machines/atomotic/b2d-image] []  <nil> 0xc82002c010 0xc82002c018 [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>} attach /Users/raffaele/.docker/machine/machines/atomotic/boot2docker.iso -mountpoint /Users/raffaele/.docker/machine/machines/atomotic/b2d-image
	(atomotic) /dev/disk3          	                               	/Users/raffaele/.docker/machine/machines/atomotic/b2d-image
	(atomotic) DBG | Extracting vmlinuz64 into /Users/raffaele/.docker/machine/machines/atomotic
	(atomotic) DBG | Extracting initrd.img into /Users/raffaele/.docker/machine/machines/atomotic
	(atomotic) DBG | Unmounting boot2docker.iso
	(atomotic) DBG | executing: &{/usr/bin/hdiutil [hdiutil detach /Users/raffaele/.docker/machine/machines/atomotic/b2d-image] []  <nil> 0xc82002c010 0xc82002c018 [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>} detach /Users/raffaele/.docker/machine/machines/atomotic/b2d-image
	(atomotic) "disk3" unmounted.
	(atomotic) "disk3" ejected.
	(atomotic) Generating 20000MB disk image...
	(atomotic) DBG | executing: &{/usr/bin/hdiutil [hdiutil create -megabytes 20000 -type SPARSEBUNDLE /Users/raffaele/.docker/machine/machines/atomotic/root-volume] []  <nil> 0xc82002c010 0xc82002c018 [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>} create -megabytes 20000 -type SPARSEBUNDLE /Users/raffaele/.docker/machine/machines/atomotic/root-volume
	(atomotic) created: /Users/raffaele/.docker/machine/machines/atomotic/root-volume.sparsebundle
	(atomotic) Creating SSH key...
	(atomotic) Fix file permission...
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/boot2docker.iso
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/config.json
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/id_rsa
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/id_rsa.pub
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/initrd.img
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/root-volume.sparsebundle
	(atomotic) DBG | /Users/raffaele/.docker/machine/machines/atomotic/vmlinuz64
	(atomotic) Generate UUID...
	(atomotic) DBG | Generated UUID: 518331EF-99AB-481E-9F89-147C845DE9A6
	(atomotic) Convert UUID to MAC address...
	(atomotic) DBG | Converted MAC address: ea:7:bc:13:cf:32
	(atomotic) Starting atomotic...
	(atomotic) DBG | [xhyve -A -U 518331EF-99AB-481E-9F89-147C845DE9A6 -c 1 -m 1024M -l com1,autopty -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-net -s 3,ahci-cd,/Users/raffaele/.docker/machine/machines/atomotic/boot2docker.iso -s 4:0,ahci-hd,/dev/rdisk3 -f kexec,/Users/raffaele/.docker/machine/machines/atomotic/vmlinuz64,/Users/raffaele/.docker/machine/machines/atomotic/initrd.img,loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 base host=boot2docker -F /Users/raffaele/.docker/machine/machines/atomotic/atomotic.pid]
	(atomotic) Waiting for VM to come online...
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 1/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG | operation not supported by device
	(atomotic) DBG | xhyve: illegal option -- F
	(atomotic) DBG | Usage: xhyve [-behuwxMACHPWY] [-c vcpus] [-g <gdb port>] [-l <lpc>]
	(atomotic) DBG |              [-m mem] [-p vcpu:hostcpu] [-s <pci>] [-U uuid] -f <fw>
	(atomotic) DBG |        -A: create ACPI tables
	(atomotic) DBG |        -c: # cpus (default 1)
	(atomotic) DBG |        -C: include guest memory in core file
	(atomotic) DBG |        -e: exit on unhandled I/O access
	(atomotic) DBG |        -f: firmware
	(atomotic) DBG |        -g: gdb port
	(atomotic) DBG |        -h: help
	(atomotic) DBG |        -H: vmexit from the guest on hlt
	(atomotic) DBG |        -l: LPC device configuration. Ex: -l com1,stdio -l com2,autopty -l com2,/dev/myownpty
	(atomotic) DBG |        -m: memory size in MB
	(atomotic) DBG |        -M: print MAC address and exit if using vmnet
	(atomotic) DBG |        -p: pin 'vcpu' to 'hostcpu'
	(atomotic) DBG |        -P: vmexit from the guest on pause
	(atomotic) DBG |        -s: <slot,driver,configinfo> PCI slot config
	(atomotic) DBG |        -u: RTC keeps UTC time
	(atomotic) DBG |        -U: uuid
	(atomotic) DBG |        -v: show build version
	(atomotic) DBG |        -w: ignore unimplemented MSRs
	(atomotic) DBG |        -W: force virtio to use single-vector MSI
	(atomotic) DBG |        -x: local apic is in x2APIC mode
	(atomotic) DBG |        -Y: disable MPtable generation
	(atomotic) DBG | exit status 1 &{0xc8200161e0} &{0xc820016210}
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 2/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 3/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 4/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 5/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 6/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 7/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 8/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 9/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 10/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 11/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 12/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 13/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 14/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 15/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 16/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 17/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 18/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 19/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 20/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 21/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 22/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 23/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 24/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 25/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 26/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 27/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 28/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 29/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 30/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 31/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 32/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 33/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 34/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 35/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 36/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 37/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 38/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 39/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 40/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 41/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 42/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 43/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 44/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 45/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 46/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 47/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 48/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 49/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 50/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 51/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 52/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 53/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 54/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 55/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 56/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 57/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 58/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 59/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	(atomotic) DBG |
	(atomotic) DBG | Not there yet 60/60, error: IP not found for MAC ea:7:bc:13:cf:32 in DHCP leases
	open : no such file or directory
	notifying bugsnag: [Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting]
	Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting

**Comment by zchee** [comment]
@atomotic Thanks issue :)

Could you try this commands?
```bash
rm -f $(which docker-machine-driver-xhyve)
go get -u -d github.com/zchee/docker-machine-driver-xhyve
cd $GOPATH/src/github.com/zchee/docker-machine-driver-xhyve
make
make install
```

**Comment by zchee** [comment]
@atomotic  Oh, I understand.

```bash
rm -f $(which docker-machine-driver-xhyve)
go get -u -d github.com/zchee/docker-machine-driver-xhyve
cd $GOPATH/src/github.com/zchee/docker-machine-driver-xhyve
make
make install
```

or,

```bash
# Need Go 1.5 vendoring support
$ export GO15VENDOREXPERIMENT=1

$ go get -u -v -f github.com/zchee/docker-machine-driver-xhyve
$ sudo chown root:wheel $GOPATH/bin/docker-machine-driver-xhyve
$ sudo chmod u+s $GOPATH/bin/docker-machine-driver-xhyve
```

**Comment by atomotic** [comment]
i had already installed using `go get`, but without **make**.  
i tried with make, now i got /usr/local/bin/docker-machine-driver-xhyve but the error is the same

**Comment by zchee** [comment]
@atomotic Hmm...

Could you try this commands?

```bash
# Cleanup all docker-machine-driver-xhyve binary
$ rm -f $(which docker-machine-driver-xhyve)
# Testing not exists docker-machine-driver-xhyve binary
$ which -a docker-machine-driver-xhyve

# Re-install docker-machine-driver-xhyve
$ export GO15VENDOREXPERIMENT=1
$ cd $GOPATH/src/github.com/zchee/docker-machine-driver-xhyve
$ make
$ make install
````

**Comment by atomotic** [comment]
nothing.

**Comment by zchee** [comment]
@atomotic nothing?
Sorry, I don't understand :(

**Comment by zchee** [comment]
@atomotic FYI, See https://github.com/zchee/docker-machine-driver-xhyve/issues/59

**Comment by atomotic** [comment]
👍it works! many thanks.

**Comment by zchee** [comment]
@atomotic :tada:
