### ISSUE TITLE
Build issue with docker v1.10

### ISSUE THREAD

**Issue by cmoad** [zchee/docker-machine-driver-xhyve#92]
Image build dies with error immediately following the `MAINTAINER` line using docker v1.10.

Sample Dockerfile:
```
FROM debian:wheezy

MAINTAINER me
```

```
Sending build context to Docker daemon 1.783 MB
Step 1 : FROM debian:wheezy
 ---> 48304f60c1b9
Step 2 : MAINTAINER me
network  not found
```

**Comment by zchee** [comment]
@cmoad Hi, thanks issue :)

I tested now, but this problem could not be reproduced :(
See asciinema: https://asciinema.org/a/35707

Could you tell me the version of related of `docker` family?

- docker
- docker-machine
- boot2docker
- docker-machine-driver-xhyve
  - Create vm  with `--debug` flag will be displayed `docker-machine-driver-xhyve` version
  - e.g. `docker-machine --debug create --driver xhyve xhyve-test`

**Comment by cmoad** [comment]
I repeated all the steps and was unable to get the error this time. I'm using homebrew for all components. docker v1.10. docker-machine v0.6.0. docker-machine-driver-xhyve v0.2.2. I guess we can call this one a glitch. Thanks for the fast response and great work on this project. It's much nicer than using vbox on osx.

**Comment by zchee** [comment]
@cmoad I was relieved to hear that :tada: 
Thanks!!

 I will keep trying my best :)
