### ISSUE TITLE
nfs share permissions problem

### ISSUE THREAD

**Issue by softinio** [zchee/docker-machine-driver-xhyve#99]
I followed your instructions for creating a vm and using the experimental nfs share. The issue I have hit is that inside the vm/containers the share doesn't have permissions to write (ie create new folders and files).

Any suggestions? 

If this is a bug I am happy to try to fix it.

I really like your project and am happy to  contribute to your project if you can give me a quick walkthrough your code. Will help with other issues being reported.

Thanks.

**Comment by zchee** [comment]
@softinio Now merged https://github.com/zchee/docker-machine-driver-xhyve/issues/105
Could you test it?
